version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "local"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:29092"
      KAFKA_CLUSTERS_0_ZOOKEEPER: "zookeeper:2181"
  spark-master:
    image: apache/spark:latest
    container_name: spark-master
    environment:
      SPARK_MODE: "master"
    ports:
      - "8090:8080"
      - "7077:7077"

  spark-worker:
    image: apache/spark:latest
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: "worker"
      SPARK_MASTER_URL: "spark://spark-master:7077"
    ports:
      - "8081:8081"

  producer:
    build: .
    container_name: bitcoin-producer
    depends_on:
      - kafka
    command: python bitcoin_producer.py
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    restart: "no"
    networks:
      - default

  spark-streaming:
    build: .
    container_name: spark-streaming
    depends_on:
      - kafka
      - producer
    command: python spark_realtime_ml.py
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
    volumes:
      - ./checkpoint:/app/checkpoint
      - ./bitcoin_model:/app/bitcoin_model
      - ./model_metrics.txt:/app/model_metrics.txt
    restart: unless-stopped
    networks:
      - default

  api-service:
    build: .
    container_name: api-service
    depends_on:
      - spark-streaming
    command: python api_service.py
    ports:
      - "8000:8000"
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
    volumes:
      - ./bitcoin_model:/app/bitcoin_model
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    driver: bridge
